version: 1.0.{build}
clone_folder: c:\src\es-theme-carbon
build_script:
- 7z a es-theme-carbon.zip C:\src\es-theme-carbon
artifacts:
- path: '*.zip'
  name: GitHub
deploy:
- provider: GitHub
  tag: continuous
  release: continuous
  auth_token:
    secure: Jzp2SBYLkIC3plNxmxAhQNW3VLlgIWzjAIvDRZ2xgWgMN5cKZe8XuJqbrQDYsGSo
    
