version: 1.0.{build}
build: off
deploy:
- provider: GitHub
  tag: continuous
  release: continuous
  auth_token:
    secure: Jzp2SBYLkIC3plNxmxAhQNW3VLlgIWzjAIvDRZ2xgWgMN5cKZe8XuJqbrQDYsGSo
    artifact: master.zip
